### ISSUE TITLE
Error Deploying to Netlify

### ISSUE THREAD

**Issue by theapplegates** [frontendweekly/virga#3]
I get a strange error when I click the deploy to Netlify button for Virga. Here is a gist to the whole error log.
https://gist.github.com/theapplegates/f6a1f185966afed1a07edc8bedf56f4d

The error for the most part is.
``
9:38:58 AM: Error: Failed to replace env in config: ${GITHUB_PKG_TOKEN}
9:38:58 AM:     at /opt/buildhome/.nvm/versions/node/v12.14.0/lib/node_modules/npm/lib/config/core.js:415:13
9:38:58 AM:     at String.replace (<anonymous>)
9:38:58 AM:     at envReplace (/opt/buildhome/.nvm/versions/node/v12.14.0/lib/node_modules/npm/lib/config/core.js:411:12)
9:38:58 AM:     at parseField (/opt/buildhome/.nvm/versions/node/v12.14.0/lib/node_modules/npm/lib/config/core.js:389:7)
9:38:58 AM:     at /opt/buildhome/.nvm/versions/node/v12.14.0/lib/node_modules/npm/lib/config/core.js:330:24
9:38:58 AM:     at Array.forEach (<anonymous>)
9:38:58 AM:     at Conf.add (/opt/buildhome/.nvm/versions/node/v12.14.0/lib/node_modules/npm/lib/config/core.js:328:23)
9:38:58 AM:     at ConfigChain.addString (/opt/buildhome/.nvm/versions/node/v12.14.0/lib/node_modules/npm/node_modules/config-chain/index.js:244:8)
9:38:58 AM:     at Conf.<anonymous> (/opt/buildhome/.nvm/versions/node/v12.14.0/lib/node_modules/npm/lib/config/core.js:316:10)
9:38:58 AM:     at /opt/buildhome/.nvm/versions/node/v12.14.0/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:115:16
9:38:58 AM: /opt/buildhome/.nvm/versions/node/v12.14.0/lib/node_modules/npm/lib/npm.js:59
9:38:58 AM: failed during stage 'building site': Build script returned non-zero exit code: 1
9:38:58 AM:       throw new Error('npm.load() required')
9:38:58 AM:       ^
9:38:58 AM: Error: npm.load() required
9:38:58 AM:     at Object.get (/opt/buildhome/.nvm/versions/node/v12.14.0/lib/node_modules/npm/lib/npm.js:59:13)
9:38:58 AM:     at process.errorHandler (/opt/buildhome/.nvm/versions/node/v12.14.0/lib/node_modules/npm/lib/utils/error-handler.js:205:32)
9:38:58 AM:     at process.emit (events.js:210:5)
9:38:58 AM:     at process._fatalException (internal/process/execution.js:150:25)
9:38:58 AM: nvm is not compatible with the npm config "prefix" option: currently set to ""
9:38:58 AM: Run `nvm use --delete-prefix v12.14.0` to unset it.
9:38:58 AM: Failed to install node version '12.14.0'
9:38:58 AM: Error running command: Build script returned non-zero exit code: 1
9:38:58 AM: Failing build: Failed to build site
9:38:58 AM: Finished processing build request in 6.598897779s
``
I'm not a developer but it seems like it is having trouble getting an NPM from your other site frontendweekly.

``
//npm.pkg.github.com/:_authToken=${GITHUB_PKG_TOKEN}
registry=https://npm.pkg.github.com/frontendweekly
``

I tried to Google a solution but could not find one that worked.

Thanks.
Paul

**Comment by theapplegates** [comment]
This is the error I get if I clone your repo and run npm install.
``
npm ERR! code E401
npm ERR! 401 Unauthorized - GET https://npm.pkg.github.com/frontendweekly/@frontendweekly%2ffilter-date-iso - Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured.
``

**Comment by theapplegates** [comment]
I don't know what token, GITHUB_PKG_TOKEN,  to put in an .env file, or even if that is the right troubleshooting step.
